### ISSUE TITLE
IPIP pool: intermittent problem with wrong routes

### ISSUE THREAD

**Issue by adidenko** [projectcalico/bird#22] opened 2016-09-16 10:08 UTC
During a number of deployment runs of Kubernetes with Calico and `--ipip` pool (deployed by Kargo) we've faced the issue with wrong routes on some (not all) nodes:

```
10.233.73.192/26 via 10.100.0.3 dev eth0  proto bird
10.233.83.64/26 via 10.100.0.2 dev eth0  proto bird
```

While it should be routed via `tunl0` interface (like on the rest of the nodes):

```
10.233.73.192/26 via 10.100.0.3 dev tunl0  proto bird onlink
10.233.83.64/26 via 10.100.0.2 dev tunl0  proto bird onlink
```

The workaround is to remove those routes via `eth0` on the problem nodes and let BIRD bring up the correct ones.

**Comment by bogdando** [comment] 2016-09-16 10:12
The solution could be perhaps to replace "ip ro add" commands to "ip ro replace" in the code :)

**Comment by fasaxc** [comment] 2016-09-16 10:15
I think you might be seeing the same issue as https://github.com/projectcalico/calico-bird/pull/21; might be worth trying the patch in that PR to see if it helps.

**Comment by bogdando** [comment] 2016-09-16 10:25
Thank you for update. Note that this issue reproduces w/o a reboot

**Comment by adidenko** [comment] 2016-09-16 10:26
Yeah, it looks like #21 may help. We'll try it, thanks!

**Comment by matthewdupre** [comment] 2016-09-20 17:37
@adidenko any update on whether that change has helped?  I'd really like to get these IPIP route tunl0 problems resolved.

**Comment by adidenko** [comment] 2016-09-21 16:39
@matthewdupre I've run several test deployments of kubernetes+calico with and without `--ipip` and I was not able to reproduce this issue.

**Comment by robbrockbank** [comment] 2017-03-29 18:08
Looks like this has now been resolved - closing out the issue.

**Closed by robbrockbank** 2017-03-29 18:08 UTC
Labels: kind/bug, priority/P2
